### ISSUE TITLE
Out of bound error in binaryReader.js

### ISSUE THREAD

**Issue by koenkooi** [tbuser/thingiview.js#1]
I cloned the project and pointed A nightly build of webkit to the examples and it gives me:

binaryReader.js:123 Error: Index out of bound

When using webkit inspector. Commenting out the throw() doesn't make it render either. I haven't looked into it more since it might be a bug in the nightly. I'll retest next week with another nightly if you think it's a bug in webkit instead of thingiview.

**Comment by tbuser** [comment]
I couldn't duplicate this, but I was just working on something else and ran into this error using Chrome, so I don't think it's webkit per se.  In my case this error meant I had passed the wrong url to load the stl and the ajax call returned no data... are you running this locally or through a web server?  I believe it needs to be on a webserver for the ajax call to work.

**Comment by koenkooi** [comment]
I was indeed running it locally

**Comment by tbuser** [comment]
You might be able to get it to work locally without a webserver if you use chrome and run it with the --allow-file-access-from-files flag, except I just tried it with my new Web Worker code and it fails even with that.  (I'm thinking it's a bug where that flag isn't being honored within worker threads)
